services:
  - type: web
    name: token-drainer-frontend
    env: static
    buildCommand: ./render-build.sh
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    envVars:
      - key: NODE_ENV
        value: production
